export const ARBOR_DEMO_NOTE = `# Story spine

The opening branch introduces the central conflict and why it matters right away.

## Character motive

The protagonist wants proof that the signal is real before the city locks everything down.

### Visual beat

![Arbor demo image](https://dummyimage.com/1200x630/241b38/e6defd.png&text=Arbor+Demo)

A screenshot-like image can live inside the same branch and survive round-trip.

## Counterpoint

A skeptic branch pushes against the main idea so the argument gets stronger while you write.

# Research branch

- Source A
- Source B

> [!note] Research note
> Keep evidence in a separate root branch while the draft is still evolving.
<!-- arbor:metadata:v1
eyJ2ZXJzaW9uIjoxLCJwcmVmaXgiOiIiLCJibG9ja3MiOlt7ImlkIjoicm9vdC1zdG9yeSIsInBhcmVudElkIjpudWxsLCJvcmRlciI6MCwiY29udGVudCI6IiMgU3Rvcnkgc3BpbmVcblxuVGhlIG9wZW5pbmcgYnJhbmNoIGludHJvZHVjZXMgdGhlIGNlbnRyYWwgY29uZmxpY3QgYW5kIHdoeSBpdCBtYXR0ZXJzIHJpZ2h0IGF3YXkuIiwiYWZ0ZXIiOiJcblxuIiwiY3JlYXRlZEF0IjoiMjAyNi0wMy0yM1QyMjowMDowMC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNi0wMy0yM1QyMjowMDowMC4wMDBaIn0seyJpZCI6InN0b3J5LW1vdGl2ZSIsInBhcmVudElkIjoicm9vdC1zdG9yeSIsIm9yZGVyIjowLCJjb250ZW50IjoiIyMgQ2hhcmFjdGVyIG1vdGl2ZVxuXG5UaGUgcHJvdGFnb25pc3Qgd2FudHMgcHJvb2YgdGhhdCB0aGUgc2lnbmFsIGlzIHJlYWwgYmVmb3JlIHRoZSBjaXR5IGxvY2tzIGV2ZXJ5dGhpbmcgZG93bi4iLCJhZnRlciI6IlxuXG4iLCJjcmVhdGVkQXQiOiIyMDI2LTAzLTIzVDIyOjAwOjAxLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI2LTAzLTIzVDIyOjAwOjAxLjAwMFoifSx7ImlkIjoic3RvcnktdmlzdWFsIiwicGFyZW50SWQiOiJzdG9yeS1tb3RpdmUiLCJvcmRlciI6MCwiY29udGVudCI6IiMjIyBWaXN1YWwgYmVhdFxuXG4hW0FyYm9yIGRlbW8gaW1hZ2VdKGh0dHBzOi8vZHVtbXlpbWFnZS5jb20vMTIwMHg2MzAvMjQxYjM4L2U2ZGVmZC5wbmcmdGV4dD1BcmJvcitEZW1vKVxuXG5BIHNjcmVlbnNob3QtbGlrZSBpbWFnZSBjYW4gbGl2ZSBpbnNpZGUgdGhlIHNhbWUgYnJhbmNoIGFuZCBzdXJ2aXZlIHJvdW5kLXRyaXAuIiwiYWZ0ZXIiOiJcblxuIiwiY3JlYXRlZEF0IjoiMjAyNi0wMy0yM1QyMjowMDowMi4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNi0wMy0yM1QyMjowMDowMi4wMDBaIn0seyJpZCI6InN0b3J5LWNvdW50ZXJwb2ludCIsInBhcmVudElkIjoicm9vdC1zdG9yeSIsIm9yZGVyIjoxLCJjb250ZW50IjoiIyMgQ291bnRlcnBvaW50XG5cbkEgc2tlcHRpYyBicmFuY2ggcHVzaGVzIGFnYWluc3QgdGhlIG1haW4gaWRlYSBzbyB0aGUgYXJndW1lbnQgZ2V0cyBzdHJvbmdlciB3aGlsZSB5b3Ugd3JpdGUuIiwiYWZ0ZXIiOiJcblxuIiwiY3JlYXRlZEF0IjoiMjAyNi0wMy0yM1QyMjowMDowMy4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNi0wMy0yM1QyMjowMDowMy4wMDBaIn0seyJpZCI6InJvb3QtcmVzZWFyY2giLCJwYXJlbnRJZCI6bnVsbCwib3JkZXIiOjEsImNvbnRlbnQiOiIjIFJlc2VhcmNoIGJyYW5jaFxuXG4tIFNvdXJjZSBBXG4tIFNvdXJjZSBCXG5cbj4gWyFub3RlXSBSZXNlYXJjaCBub3RlXG4+IEtlZXAgZXZpZGVuY2UgaW4gYSBzZXBhcmF0ZSByb290IGJyYW5jaCB3aGlsZSB0aGUgZHJhZnQgaXMgc3RpbGwgZXZvbHZpbmcuIiwiYWZ0ZXIiOiIiLCJjcmVhdGVkQXQiOiIyMDI2LTAzLTIzVDIyOjAwOjA0LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI2LTAzLTIzVDIyOjAwOjA0LjAwMFoifV0sImxhc3RMaW5lYXJIYXNoIjoiZGVtbyIsInNhdmVkQXQiOiIyMDI2LTAzLTIzVDIyOjAwOjA1LjAwMFoifQ==
-->
`;
